### ISSUE TITLE
how to type enter 

### ISSUE THREAD

**Issue by rupamking1** [shelljs/shelljs#1023]
how to type enter

**Comment by nfischer** [comment]
It's not clear what issue you're having. Can you clarify?

**Comment by rupamking1** [comment]
I want to execute multiple commends, for that reason i asked how to type enter.

**Comment by nfischer** [comment]
You can call multiple functions like so:

```js
shell.mkdir('somedir');
shell.touch('somedir/somefile.txt');
shell.rm('-rf', 'somedir');
```

If you're asking specifically about `shell.exec()`, then you can use semicolons between commands:

```js
shell.exec('git status; printf hello'); // git status + printf
```

Of course, you can also call `exec()` multiple times to execute a different command each time. `exec()` also supports `&&` and `||` operators, since all it does is create a shell and run commands in the shell. I think `;`, `&&`, and `||` are all supported on Linux, mac, and Windows.

---

Let me know if this helps. I'm going to close this ticket since it doesn't sound like there are any code changes necessary in ShellJS, but I'm happy to reopen this if I've misunderstood.
