### ISSUE TITLE
shell.exec not work

### ISSUE THREAD

**Issue by xgqfrms** [shelljs/shelljs#1048]
# shell.exec not work

### Node version 

> v12.18.0

### ShellJS version 

```js
  "dependencies": {
    "shelljs": "^0.8.4"
  }

```

### Operating system:

> macOS 10.15.7

### Description of the bug:

> wanted

```sh

$ ./spe.js  PORT_ENV=666 && node ./test.js
# ✅
# test command = export PORT_ENV=666
# PORT_ENV = 666
# PORT_ENV =  666

```

> actually 

```sh

$ ./spe.js  PORT_ENV=666 && node ./test.js
# ❌
# test command = export PORT_ENV=666
# PORT_ENV = undefined
# PORT_ENV = undefined

```

### Example ShellJS command to reproduce the error:

> spe.js

```js

#!/usr/bin/env node

/**
 *
 * @author xgqfrms
 * @license MIT
 * @copyright xgqfrms 2021.10.14
 *
 * @description Pset-process-env
 *
 */

 const shell = require("shelljs");

const fs = require("fs");

const {
  version,
  argv,
  platform,
} = process;

const isMac = (platform === 'darwin');

const args = argv.slice(2) || [];

const isPureNumber = (str = '') => {
  const numberDict = [...''.padEnd(10, 'x')].map((item, i) => `${i}`);
  const arr = `${str}`.split('');
  return arr.every(item => numberDict.includes(item));
}

let key = "";
let env = "";
if (!args[0]) {
  args[0] = "";
  key = 'PORT_ENV';
  env = 8080;
} else {
  const tempArr = args[0].split('=');
  key = tempArr[0] || 'PORT_ENV';
  env = isPureNumber(tempArr[1]) ? parseInt(tempArr[1]) : tempArr[1];
}

let command = ``;

  if(isMac) {
    command = `export ${key}=${env}`;
  } else {
    command = `set ${key}=${env}`;
  }


shell.exec(command);

console.log('\n test command =', command);
console.log('\n PORT_ENV =', process.env.PORT_ENV);

```

test.js

```js
// console.log('process.env =', process.env);
console.log('PORT_ENV =', process.env.PORT_ENV);


```

**Comment by nfischer** [comment]
Can you help me clarify my understanding?

It sounds to me like you want to define `PORT_ENV` env variable in one script (`spe.js`) and read the value in a different script (`test.js`). Please note that environment variables are visible to subprocesses, but not sibling processes. So this would work if `spe.js` directly executes `test.js`. The reason this doesn't work for you is because `spe.js` finishes execution before `test.js` starts, so all of `spe.js`'s environment variable changes have been reset.

I'm tentatively closing this based on this understanding. Please let me know if I've misunderstood and I'll reopen this.

**Comment by xgqfrms** [comment]
@nfischer you are right, it's not a bug, thanks for your time!
