### ISSUE TITLE
shelljs.which('node') return null in Electron production

### ISSUE THREAD

**Issue by sufangyu** [shelljs/shelljs#1089]
shelljs.which('node') return null in Electron's production mode.

System: Mac.

shelljs.which('node') return value in Electron's production mode.

**Comment by nfischer** [comment]
What is the output of running `which node` in the terminal?

What is the value of `shell.env.PATH` (running within electron)?

**Comment by sufangyu** [comment]
@nfischer shell.env.PATH value：'/usr/bin:/bin:/usr/sbin:/sbin'

**Comment by ilan-pinto** [comment]
note that when o have manually added the node path configuration  
`shell.config.execPath = "/usr/local/bin/node";`
and than executed: 
`shell.exec('clusteradm version');`
i got the following err: '[/bin/sh](): kubectl: command not found\n'

my default shell is zsh. 
which makes me wonder if that might be related to the issue

**Comment by nfischer** [comment]
@sufangyu and what is the output of `which node` in the terminal?

@ilan-pinto your issue sounds unrelated to this report. "command not found" probably means you're missing the `kubectl` command on your system. Maybe double check that you've installed `clusteradm` and `kubectl` correctly.

**Comment by sufangyu** [comment]
> @sufangyu and what is the output of `which node` in the terminal?
> 
> @ilan-pinto your issue sounds unrelated to this report. "command not found" probably means you're missing the `kubectl` command on your system. Maybe double check that you've installed `clusteradm` and `kubectl` correctly.

which node：/usr/local/bin/node

**Comment by nfischer** [comment]
It looks like electron is changing your `$PATH` variable. If the `node` binary lives in `/usr/local/bin/` then your `shell.env.PATH` value needs to include that folder in the list. This is probably in the list by default on your system (otherwise `which node` would have failed), so you'll need to do some digging to understand why electron is modifying that for you.

Unfortunately there's nothing ShellJS can do to workaround this. We just make do with the `$PATH` provided to us from the environment.

**Comment by ilan-pinto** [comment]
@nfischer I revalidated the binaries of  clusteradm and kubectl are installed

**Comment by ilan-pinto** [comment]
I found a solution. 
apparently, VScode does not load experimental shells like zsh unless you specify it under 
`terminal.integrated.shell integration you need enable it and restart the process

**Comment by nfischer** [comment]
> that it executes the commands using bin/sh while i have zsh configured in the shell.env

`shell.exec()` uses the `sh` shell by default. If you want to change to shell to something else, you're probably asking too much from `shell.exec()`. This is designed for running single commands, not executing complex shell expressions.

**Comment by ilan-pinto** [comment]
@nfischer apparently some Mac's don't have sh

**Comment by nfischer** [comment]
Do you have a source for that statement? I couldn't find anything in a quick google search, but I could be out of date.

[Apple configured new versions of MacOS to use zsh as the default login shell](https://www.theverge.com/2019/6/4/18651872/apple-macos-catalina-zsh-bash-shell-replacement-features) for interactive sessions. This is not the same thing as "some Mac's don't have sh" though, and it should still be perfectly fine for `shell.exec()` to invoke `/bin/sh` for programmatic use. Unix-y systems may alias `/bin/sh` to different things under the hood (ex. [zsh in POSIX mode](https://unix.stackexchange.com/questions/38172/are-all-bash-scripts-compatible-with-zsh#:~:text=Zsh%20can%20run%20most%20Bourne,for%20any%20script%20you%20have.), [bash in POSIX mode](https://www.gnu.org/software/bash/manual/html_node/Bash-POSIX-Mode.html), [dash](https://wiki.ubuntu.com/DashAsBinSh)), but generally there's at least _something_ located at `/bin/sh` and that shell is usually POSIX compliant. If some macs don't have sh anymore (or have it at a different path), then that's news to me.

`shell.exec()` supports changing the shell with the `shell` option: https://github.com/shelljs/shelljs#execcommand--options--callback (see "and any option available to Node.js's child_process.exec()"). But like I said before, if you're changing the shell because you're loading lots of shell syntax into `shell.exec()`, then you're probably trying to do too much work in `shell.exec()`.
