### ISSUE TITLE
 Cannot find module 'shelljs' after installing shelljs with npm

### ISSUE THREAD

**Issue by raphaelcruzeiro** [shelljs/shelljs#109]
I have installed shelljs with npm with no problems:

```
npm install shelljs -g
```

But when I try to import shelljs into my project I get the error:

```
var shell = require('shelljs');

Error: Cannot find module 'shelljs'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at repl:1:2
    at REPLServer.self.eval (repl.js:110:21)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.EventEmitter.emit (events.js:95:17)
    at Interface._onLine (readline.js:202:10)
    at Interface._line (readline.js:531:8)
```

I have trying installing shelljs both globally and locally. I am using OS X Mavericks 10.9.2. Npm lists shelljs as installed:

```
shelljs@0.2.6 /usr/local/lib/node_modules/shelljs
```

**Comment by clintonmedbery** [comment]
What I had to do:
1) Type in `npm -root -g`
2) The last line will look like `npm@6.7.0 /Users/clintonmedbery/.nvm/versions/node/v6.5.0/lib/node_modules/npm`
3) Take the path minus /npm and export is as NODE_PATH: `export NODE_PATH=/Users/clintonmedbery/.nvm/versions/node/v6.5.0/lib/node_modules`
4) Run `npm install -g shx` instead of install shelljs (https://github.com/shelljs/shx/issues/24)

**Comment by nfischer** [comment]
@clintonmedbery I think step 1 should be `npm root -g`, right?

Steps 1-3 seem to be about npm prefix. If you change the npm prefix (`npm config set prefix ...`), or you use `nvm` (which changes the prefix for you), then you're responsible for setting `NODE_PATH` accordingly. This is not specific to ShellJS, but rather applies to any packages installed with `-g`.

In practice, I recommend against using `-g` when installing library-packages, like ShellJS, since you should commit dependency info in `package.json` (`npm install -S`). It's still OK to `npm install -g` executable-packages, like shx.

As for step 4, you **do not** need to install `shx` to use ShellJS (shelljs/shx#24 was never relevant to ShellJS). shelljs/shx#24 is about a quirk of pre-release `shx`: we've released it since then, so it's no longer relevant to `shx` either. Only install shx if you actually want to use that command.

**Comment by clintonmedbery** [comment]
Thanks for the insight. I updated my comment!
