### ISSUE TITLE
Feature request (true, false)

### ISSUE THREAD

**Issue by nicky1038** [shelljs/shelljs#1128]
Linux has `true` command, this command does nothing and always succeeds. The opposite to it is `false`: it also does nothing but always fails.

Sometimes they can become very useful, still on Windows just typing `true` or `false` don't work, one needs to write some workarounds.

So it would be useful to have these two commands as a part of this beautiful library.

In certain cases `exit 0` or `exit 1` could be used instead, but these commands, unlike `true` and `false`, stop current process, that may not be desirable.

**Comment by nfischer** [comment]
We actually have a plugin implementation of these in the [shelljs/shx](https://github.com/shelljs/shx) repo (the source code is here: https://github.com/shelljs/shx/blob/main/src/plugin-true-false.js). I didn't upstream these functions into ShellJS itself because it doesn't seem like these commands would be very useful in this context, since they would basically just be NOOP functions with a side-effect of modifying the `shell.error()` state.

If you only need this in a commandline context, try out:

```sh
npm install -g shx
shx true && echo "true works"
shx false || echo "false works"
```
