### ISSUE TITLE
A problem with cd outside the project

### ISSUE THREAD

**Issue by cvecina** [shelljs/shelljs#1157]
### Node version (or tell us if you're using electron or some other framework):
Using Nuxt 3 - node version v21.6.2

### ShellJS version (the most recent version/Github branch you see the bug on):
0.8.5

### Operating system:
Mac OS 14.4.1 (23E224) (Sonoma)

### Description of the bug:
I'm trying to cd to the home directory (using 'os' library) and list the data (ls -l) and i get this error:

 ERROR  cd: not a directory: /Users/razor

and the ls -l command is executed on the project folder.

is possible to cd to another folder outside the project?

### Example ShellJS command to reproduce the error:

import os from "os";
import shell from "shelljs";

const homedir = os.homedir();

const listarArchivosDeCarpeta = async () => {
    shell.cd(homedir);
    shell.exec("ls -l");
}

export default defineEventHandler(async (event) => {
    await listarArchivosDeCarpeta();
})

**Comment by cvecina** [comment]
i tried to create with mkdir using shell.mkdir and cd it, and i can't cd inside the project too.

example:

shell.mkdir('prueba')
shell.cd('prueba')
shell.exec('ls -l')

the ls -l works correctly on main folder, it shows that exists the new 'prueba', but the cd returns the same error. ERROR cd: not a directory: /prueba

**Comment by nfischer** [comment]
What is nuxt 3?

Can you try this in plain old nodejs? `shell.cd()` is supposed to work for basically any folder—as long as you have permission to enter that folder, `shell.cd()` should handle it.

**Comment by nfischer** [comment]
I think this is a problem caused by nuxt, so it is not something we can workaround. ["In development, [nuxt] uses... workers."](https://nuxt.com/docs/getting-started/introduction#:~:text=In%20development%2C%20it%20uses%20Rollup%20and%20Node.js%20workers) This is a known limitation of workers and it's not something we can workaround: ["process.chdir() and process methods that set group or user ids are not available"](https://nodejs.org/api/worker_threads.html#:~:text=process.chdir()%20and%20process%20methods%20that%20set%20group%20or%20user%20ids%20are%20not%20available).

If process.chdir() is not allowed, then shell.cd() simply cannot ever work. You should find a way to workaround this on your end.
