### ISSUE TITLE
touch command

### ISSUE THREAD

**Issue by slang800** [shelljs/shelljs#122]
I'd find this useful, and there's already a package for doing it here: https://github.com/isaacs/node-touch. It just needs to be fitted to work with the shelljs interface.

Thoughts?

**Comment by n2liquid** [comment]
This is from 2014 and there's still no touch command? I'm not trying to be a prick, but how come this project doesn't have that?

**Comment by slang800** [comment]
oh - I totally forgot about this issue.
@Schoonology - why don't you want deps?

**Comment by Schoonology** [comment]
@arturadib can chime in with other reasons, but my biggest reason is keep the installation process of shelljs as simple, fast, and low-risk as possible.

I understand that `touch` is a relatively simple module in practice, but it brings along with it `nopt`, an option parser, because `touch` includes a `bin` script. It's well within the realm possibility that some native library is found to implement `nopt`'s philosophy, only faster. If `nopt` decides to use this library in lieu of parsing arguments in JavaScript, then we have a native dependency because we use `touch`.

Granted, the likelihood of this happening may be low, but situations like this happen all over Userland, and we have _a lot_ of users' expectations to manage. The most common use case seems to be normalizing a shell environment where little may be known about what other tools are available, and I'd rather be able to guarantee `shelljs` can install with nothing but `node`, not a compiler toolchain and Lord Knows What Else.

**Comment by n2liquid** [comment]
If touch needs native deps, I think that's a good enough reason to leave it out. It's not like I can't install node-touch alongside shelljs if I need it anyway. They can be like Batman and Robin or something.

**Comment by devTristan** [comment]
To add dependencies while (mostly) guaranteeing future stability, npm's [shrinkwrap](https://docs.npmjs.com/cli/shrinkwrap) feature can be employed. That way, any dependency (or sub dependency) changes must be signed off on and cannot be brought in automatically.

**Comment by slang800** [comment]
touch doesn't need native deps... AFAIK, it's pure JS and so is nopt

**Comment by arturadib** [comment]
it looks like `touch.js` from `node-touch` is merely ~150 lines of JS code, we could bring it over and adapt it to the way we handle arguments (so as to not use `nopt`).

I've been favoring this method of implementing features mostly because (like `touch`) most commands are only ~100 lines long, and so mapping our way of handling arguments and options to a library's isn't worth the trouble.

@n2liquid you're welcome to send a pull request! manda brasa, valeu :)

**Comment by slang800** [comment]
...or we could fork it into a new library (the 150 lines of JS w/out nopt), then make both node-touch and shelljs depend upon that micro-library. Then way collaborators from both projects would be maintaining the same code.

**Comment by nfischer** [comment]
Closing this, since we merged #249
