### ISSUE TITLE
Escaping shell arguments to exec()

### ISSUE THREAD

**Issue by d11wtq** [shelljs/shelljs#143]
First of all, I just want to say thanks for writing shelljs. It cleans up my code a lot.

I need to invoke commands with `shell.exec()`, however, those commands will include some input from external sources, to be passed as arguments to system executables. Is there a "safe" way to do this? I was hoping for the classic array syntax, like:

``` javascript
shell.exec(["ls", "-l", "/some/path"])
```

Though this doesn't seem to be implemented. It doesn't appear nodejs itself even has a shell escape function neither. Any plans on this front?

**Comment by Nieralyte** [comment]
+1

**Comment by prankymat** [comment]
+10000000

**Comment by nfischer** [comment]
@d11wtq we don't currently support an array syntax for `exec()`, but you can achieve that with `['ls', '-A', '/path/to/dir'].join()`.

Or is your concern about escaping values (such as how `printf "\\"` is written as `exec('printf "\\\\"')` in shelljs)?

**Comment by cscott** [comment]
*Please*.  Providing only a string argument here is a recipe for disaster, honestly.  As pointed out, it's basically impossible to "properly" quote any arguments given.  As is, `exec` is vulnerable to file names containing spaces, special characters, semicolons, the works. Cf http://www.dwheeler.com/secure-programs/Secure-Programs-HOWTO/handle-metacharacters.html and the "motivation" section of (for example) https://www.python.org/dev/peps/pep-0324/.  A security-conscious API should strongly encourage providing arguments as an array by default.

**Comment by nfischer** [comment]
Looks like this might be related to #103.

@cscott The concern is that, under-the-hood, we rely on Node's child_process module (specifically, `exec()` and `execSync()`. According to [the docs](https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback), these only support a string argument. So although we could write something to allow `exec()` to take an array, I suspect we'd have to `.join()` the strings anyway.

> As pointed out, it's basically impossible to "properly" quote any arguments given.

Could you give an example where it's impossible to quote arguments? I thought it was just a matter of escaping the appropriate characters, i.e. `exec('head file\\ with\\ spaces.txt')`. The point of exec is to take a string like you'd use for a `/bin/bash` command.

Maybe it would be better to expose a function for shell-escaping? Then we can write things such as:

```javascript
// This gives us an alternative syntax
exec('printf "\\\\"'); // this works, but that's lots of backslashes! Very error-prone
exec(shellEscape('printf "\\"')); // this looks like the bash command: `printf "\\"`

// or, this example
ls('src/').forEach(function (fileName) {
  exec('head ' + shellEscape(fileName)); // it's safe to use the output of ls() now
}
```

**Comment by cscott** [comment]
`child_process.execFile` takes separated arguments -- as does the
underlying c function.  The point is to avoid using the shell (bash or
whatever) where it is not necessary, which avoids having to
reverse-engineer the shell's parsing algorithm and avoids any shell-related
exploits.  The point is to provide a mechanism that is "secure by default"
and force folks to jump through a few hoops perhaps if they need to do
something insecure --- not to provide an "insecure by default" interface
and hope that all clients remember to use the appropriate escape functions
(hint: they won't).

**Comment by cscott** [comment]
Just spitballing potential issues with "just the quotes" escaping -- what happens if you follow a Unicode surrogate character with a quote.  Does node/bash treat that as an actual quote, or as a invalid utf character (and replace it with a different utf character)?  Is this the same on all platforms and all shells?

This is just the first example I can think of---I guarantee you that if you are passing untrusted values to the shell via string concatenation and relying on naïve escaping  you will find plenty of similar edge cases and surprises.  This is really security 101.

**Comment by nfischer** [comment]
@cscott from the docs for ShellJS's `exec()`:

> Executes the given command synchronously, unless otherwise specified.

Since it says the word "command," I argue that this should, by default, behave like executing a command in the shell (we don't call them "commands" in C and other relevant languages). I interpret `exec('git status')` as translating to `git status`, although I suppose another valid interpretation is translating to `exec git status`. Either way, however, these commands respect special characters (I don't see it as a security flaw, per se, since I think glob characters are a nice feature).

I'm not opposed to secure code. `exec()` is not the only function that can have unintended effects due to glob characters:

```Bash
# in an empty directory
$ touch a.txt # creates a normal file
$ touch b.txt # again, works as expected
$ touch *.txt # does not create a file, this just updates time stamps for the other two
$ touch '*.txt' # this creates a file named *.txt
$ for k in *.txt; do echo $k; done # no quotes around $k is insecure
a.txt
b.txt
a.txt b.txt *.txt
$ for k in *.txt; do echo "$k"; done # double quotes allow $k to work sensibly
a.txt
b.txt
*.txt
```

One thing that's unique about exec is if you try `exec('git add ' + filename);`, where `filename` is actually the string `test.txt;rm -rf ~`. That's a valid filename, and if we allow code to create that file, the user then does an `ls()` & `exec(cmd + filename)` loop, they would get unintended side effects.

The point being, we can't just have one solution for `exec()`, because that doesn't really solve the issue for the other commands. Would you be opposed to exposing an `execFile()` *alternative* for `exec()` that handles the case involving characters like semicolons, redirection, etc. in a non-shell way, more similar to C's `exec()` system call?

**Comment by nfischer** [comment]
Actually, a better idea would be to add an option to exec called "noGlob". When true, all characters are treated literally (as if the shell argument were wrapped in single quotes, or like an argument passed to C's execvp system call). As well as an explicit shellEscape function that prevents glob expansion on its arguments

**Comment by cscott** [comment]
I'm not opposed to an `execFile` alternative.  But I'd be much happier with
an option called `glob` or `shell` that enabled the dangerous functionality
for those who actually want/need it, and left most users "safe by default".​

**Comment by nfischer** [comment]
@cscott Here's what I'm thinking the interface should look like.

```Javascript
exec(cmd); // this will use a default value for glob (haven't decided if that should be false or true)
exec(cmd, {glob: true}); // '*' expands like a shell glob. Other characters have special meanings
exec(cmd, {glob: false}); // ';', '*', '?', '>' are all taken literally
exec(arg1, arg2, arg3); // executes something like `'arg1' 'arg2' 'arg3'` in the shell. arg2 could have a space, and it will still count as one argument
exec(arg1, arg2, arg3, {glob: true}); // arg2 can have a space, but it will still be one argument. * is a glob character
exec(arg1, arg2, arg3, {glob: false}); // same as above, but * is a literal *. ? is a literal ?. Etc.
```

The question remains, should this option be named `glob`, `noGlob`, `shell`, etc.? I'm leaning toward `glob` or `shell`, depending on what behavior it really provides. Also, we also have to figure out its default value (true or false). Could you provide some example ShellJS scripts that exhibit potentially unintended behavior?

Also, while we're on the subject, it may be worth considering adding a `-f` option to `set()` to disable globbing (see https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html). I think we should migrate to supporting globbing by default on **all** commands, so `set('-f')` would be a nice way to let people have extra-safe code.

**Comment by ariporad** [comment]
@nfischer: +1 on `set('-f'). IMHO, option should be `glob`, should be `true` by default. The rest of your idea looks great.

**Comment by ariporad** [comment]
I've got an idea for an API:

What if we did this (using ES6 string tags):

$`mycommand --opt ${unsafeVar}`
That gets transpiled to:

$('mycommand --opt ', unsafeVar);
Which is a totally acceptable syntax for <ES6.

**Comment by nfischer** [comment]
@cscott Although I think we may try to add in the `execFile`-like interface for shelljs proper, here's an extension I wrote that handles *most* (not all!) of the security concerns raised in this issue:
https://github.com/nfischer/shelljs-exec-proxy

**Comment by knownasilya** [comment]
I would like to see @ariporad's suggestion implemented, making multi-line scripts possible as well (I think..).

**Comment by ariporad** [comment]
Ok, so I finally had a moment to stop and think about ShellJS, so here's what I learned:

I misread the docs... I had the ES6 syntax right, but the ES5 syntax would be like this:

```javascript
shell(['git doThing --foo', '--bar'], unsafeVar, unsafeVar2);
```

Which is a bit awkward.... that could also lead to the problem that if someone gets it wrong, and does this:

```javascript
shell(['git doThing --foo', unsafeVar, '--bar', unsafeVar2]);
```

They actually won't be escaped, leading to bugs (or worse, security holes). It's also tricky to check against that case (only an array passed), because: 

```javascript
shell`git thingWithoutArgs`; // Becomes:
shell(['git thingWithoutArgs']);
```

So, our options would be:

```javascript
// Option 1:
shell.tag`unsafe --thing ${unsafeVar}`

// Option 2 (sorry for the pseudocode):
function shell(strings, ...values) {
    if (strings.length === 1 && values.length === 0) {
        shell.normalExec(strings[0]);
    }
    if (Array.isArray(strings) && strings.length > 1 && values.length === 0) {
        child_process.execFile(...strings);
    }
    // Do the actual thing.
}

// Option 3:
shell('command', unsafeVar, '--arg', unsafeThing2);
```

Thoughts?

**Comment by mikeatlas** [comment]
Ouch, 2+ year-old, high-priority security vulnerability? No consensus or fix yet?

**Comment by nfischer** [comment]
@mikeatlas I've got something sitting on my computer that'll fix the security issues (it's a new API which would soft-deprecate `exec`). I've been waiting to push a PR because:

 1. I'm not sure how I feel about the interface (but we can open that up to community discussion).
 2. It still relies on the file system for IPC, which I don't really like. I'm still experimenting to see if there's a way to get IPC off the file system, but we've looked it up in the past and haven't found any sort of solution.

I'll test on Windows and open up a PR tonight or tomorrow, tagging the relevant issues.

**Comment by cscott** [comment]
I have a mild preference for `glob:false` by default, since if you need a glob you're likely to know it, whereas you are probably not going to stop to think "what if the user passes a string with a literal wildcard here, where i'm expecting a filename"?

But the important part (from my perspective) is glob or no glob, don't split arguments on spaces and use node's execFile instead of trying to build a string command.

**Comment by nfischer** [comment]
I think the most important is to avoid command injection, which my implementation will fix. It's based off `spawn` instead of exec file, but the two are mostly interchangeable (I think this separates it further from exec, to alleviate confusion).

**Comment by OmgImAlexis** [comment]
Are there any updates on this? This has been open for 3 years now.

Ref: https://snyk.io/vuln/npm:shelljs:20140723

**Comment by zmorris** [comment]
For anyone who gets here looking for something like PHP's [escapeshellarg()](http://php.net/manual/en/function.escapeshellarg.php), **nfischer** implemented a rather slick way of calling shell commands via proxy and passing unsafe arguments as parameters:

https://github.com/shelljs/shelljs/issues/143#issuecomment-229830399

https://github.com/nfischer/shelljs-exec-proxy

```
yarn add shelljs-exec-proxy
# or
npm install shelljs-exec-proxy
```
```
const shell = require('shelljs-exec-proxy');
```
```
const myUrl = "google.com ; echo You have been pwned";

shell.curl(myUrl);
// prints: Could not resolve host: google.com ; echo You have been pwned

shell.exec('curl ' + myUrl);
// prints: You have been pwned
```

**Comment by nfischer** [comment]
Bumping these back to v0.9, but this should be quick to fix once v0.8 is released.

**Comment by ipsquare** [comment]
can someone please update/resolve this issue please

**Comment by nfischer** [comment]
Merging into #495, which is starting to see some traction (see #866).

Design doc: https://shelljs.page.link/cmd-design

**Comment by nfischer** [comment]
Can you try this out in the latest ShellJS release (v0.9.1) and let me know if that fixed the problem?

This should be supported by the new [`shell.cmd()`](https://github.com/shelljs/shelljs#cmdarg1-arg2---options) function, which is intended as the replacement for most uses of `shell.exec()`.
