### ISSUE TITLE
exec() breaks if executed in a deleted directory

### ISSUE THREAD

**Issue by amjibaly** [shelljs/shelljs#157]
Sample:

```js
$ node
> sh = require('shelljs')
> sh.mkdir(sh.tempdir() + '/deleteme')
> sh.cd(sh.tempdir() + '/deleteme')
> sh.rm('-rf', sh.tempdir() + '/deleteme')
> sh.exec('echo hi')
```

This works in bash:
```bash
$ mkdir /tmp/deleteme
$ cd /tmp/deleteme/
$ rm -rf /tmp/deleteme/
$ echo hi
hi
```

**Comment by ariporad** [comment]
@nfischer: What do you think about this? I'm not really sure if we should support this. (Nor if it's possible, because we execute each command separately, and we can't cd into a deleted directory).

**Comment by nfischer** [comment]
I don't think we should support this.

 1. I'm not sure how we would, since `exec()` forks a shell, which has to start in some directory (and cwd makes the most sense)
 2. I don't think this affects a large number of users
 3. It actually does work if you swap `exec(...)` with the native shelljs `echo()`

I vote to close this issue. @amjibaly if you really need this behavior, provide a more useful example and I'll gladly reconsider.

**Comment by ariporad** [comment]
Me too... Closing. @amjibaly: feel free to reopen if you have useful example.
