### ISSUE TITLE
exec failed to return

### ISSUE THREAD

**Issue by qiluo** [shelljs/shelljs#208]
I'm trying to call

```
exec('cmd <<< "dir"')
```

the command failed to return, don't know if it's related to `cmd <<<`

**Comment by nfischer** [comment]
I tried running the following commands, and saw this output:

```
$ node
> require('shelljs/global');
{}
> exec('cat <<< "dir"');
/bin/sh: 1: Syntax error: redirection unexpected
{ code: 2,
  output: '/bin/sh: 1: Syntax error: redirection unexpected\n' }
```

This suggests that `exec()` uses `sh`, not `bash`. When I try emulating this in `sh`, I see comparable output:

```sh
$ sh # make sure I'm using sh instead of bash
$ cat <<< "dir"
sh: 1: Syntax error: redirection unexpected
```

So this sounds like you're using syntax that isn't supported by `sh`, and therefore won't be supported by `exec()`.

It might be worth it to modify `exec()` to call bash instead of sh, but this would change the project's behavior, so it should only be done with some hesitation.

**Comment by ariporad** [comment]
@nfischer: I think that we should switch to bash, it would likely be more intuitive.

**Comment by nfischer** [comment]
@ariporad I agree, I think bash would be better. I think it's ok for now to put this off, since we're at least matching `sh`, but we may want to move forward and switch to bash in the near future.

**Comment by nfischer** [comment]
I opened #281 to discuss switching shells

**Comment by nfischer** [comment]
@qiluo this should be fixed by #335, which is in v0.6. See the `shell` option for Node's [child_process.exec](https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback).

**Comment by nfischer** [comment]
Whoops! Looks like #335 doesn't quite fix this. I'm opening #348 to actually resolve the issue like I suggested (and it adds a test to make sure).

**Comment by nfischer** [comment]
#348 is now merged, so this should fix the issue. You should be able to use `exec('echo foo', {shell: '/bin/bash'})` to do what you need (assuming that's your path to bash, of course).
