### ISSUE TITLE
Not possible to check the failure of cd?

### ISSUE THREAD

**Issue by jakub-g** [shelljs/shelljs#247]
Platform: Windows 7, node 0.12.7

It seems that there's no easy way to check for error of shelljs' `cd`. When trying to `cd` to non-existent folder:

- it doesn't throw
- the return value of the command is `null` (it seems it's `undefined` for successful cd, but the distiction is accidental I guess, nothing to rely on reliably)
- it only displays an error to stdout (not stderr) and that's it.

**It seems that I could check if `cd` succeeded, by getting `process.cwd()` and comparing it to desired location (and using `path.normalize()` to account for relative paths, Windows paths scheme etc), but it seems verbose.**
Probably it would make sense to write your own wrapper which does `shelljs.cd`, verifies, and does something (abort script?) when it failed.

What is your preferred way of checking for errors of `cd`?
Do you think it would be useful to do some change in shelljs to better handle this?

This is my script:

```
#!/usr/bin/env node

var path = require('path');

try {
  var desiredTarget = 'd:/gh/doesNotExist';
  // var desiredTarget = 'd:/gh/test-shelljs';
  var out = require('shelljs').cd(desiredTarget);

  console.log("OUT:                  " + out);
  console.log("CWD:                  " + path.resolve(process.cwd()));
  console.log("path.resolve(target): " + path.resolve(desiredTarget));
} catch (e) {
  console.log("ERROR" + e);
}
```

and tests:

```
    me@mymachine /d/gh/test-shelljs   # desiredTarget = 'd:/gh/test-shelljs';
    $ ./test.js
    OUT:                  undefined
    CWD:                  d:\gh\test-shelljs
    path.resolve(target): d:\gh\test-shelljs

    me@mymachine /d/gh/test-shelljs   # desiredTarget = 'd:/gh/doesNotExist';
    $ ./test.js
    cd: no such file or directory: d:/gh/doesNotExist

    OUT:                  null
    CWD:                  d:\gh\test-shelljs
    path.resolve(target): d:\gh\doesNotExist
```

**Comment by nfischer** [comment]
In my opinion, this is something that needs to be added to the project.

I think this is an issue in general with commands: they don't seem to return errors in a sensible way. Bash returns errors as return codes, and continues on. Since return values are already used for stdout usually (such as with `ls()`), that rules this out.

Changing this to return an object with fields like stdout, stderr, and return code would solve the issue, but might be cumbersome. This would likely break lines like `echo(ls())`, since `ls()` would now return an object, not an array. Lines such as `if(pwd() === '/home/myusername')` would be even trickier to fix.

Like you said above, if we throw an exception, that would indicate the error, but would diverge pretty far from shell scripts, since those continue through errors (`cd myfakedir/; echo hi` will always print "hi", regardless if `myfakedir/` exists).

One thought is to set a global variable for the return status of the last command. This would get updated by every command. Then you could check its value much like one might do in bash with `$?`:

```Bash
cd myfakedir/
if [ $? == 0 ]; then
  echo "it exists"
else
  echo "fake directory"
fi
```

**Comment by nfischer** [comment]
* If you want an invalid `cd()` to abort the script, you can always set the `config.fatal` value (see the docs)
 * If you'd prefer for it not to abort, but would like to check errors, you can use the `error()` function as seen above

I'll close this issue for now. If this isn't sufficient, please reopen the issue or ping this thread explaining what else you need.
