### ISSUE TITLE
why not support set 'cwd'  when invoke execAsync ?

### ISSUE THREAD

**Issue by houfeng0923** [shelljs/shelljs#250]
https://github.com/shelljs/shelljs/blob/v0.5.3/src/exec.js#L140

**Comment by TimothyGu** [comment]
`cd`?

**Comment by nfischer** [comment]
I agree that the simplest thing to do is probably to just say something like:

```Javascript
cd('foo');
exec('git status');
cd('..');
```

@houfeng0923 is this good enough?

**Comment by nfischer** [comment]
I'm closing this for now, since a `cd()` should do what @houfeng0923 describes. If this isn't sufficient (or there's a nice syntax available in Bash that we should emulate), please ping this thread and we can reopen it.

**Comment by nfischer** [comment]
Reopening this because I realized this actually is a concern. `child_process.execSync` seems to behave differently on Windows (**and it's totally breaking the entire test framework for me**).

On unix, `exec()` will keep the same directory it's executed from (which is intuitive). On Windows, `exec()` will always start from the *user's home folder* (this is because `cmd.exe` must be spawned first).

I still think that my suggest comment **should** be the way of achieving the desired behavior, however this isn't possible on Windows as-is. I think our `exec()` should always start from the current directory (which is in-line with how Bash behaves for commands).

**Comment by nfischer** [comment]
So I'll be closing this again, since I think my Windows system is just peculiar about `exec()`. Everything passes Windows CI now, so unless more people have the issue I described, let's leave it for now.

For the record, this could be resolved by #163 if we decide to move forward in this direction.
