### ISSUE TITLE
v0.6.0 - shell.cp('r', '/foo/*, '/bar') fails with /foo/* no such file or directory

### ISSUE THREAD

**Issue by gruenebe** [shelljs/shelljs#342]
Hi,

I am using shelljs for a long time now. My Jenkins always pulls the latest version and until v0.5.3 everything works nice. But with 0.6.0 something broke. 
When I do:

```
var font = {
        font: 'fontawesome',
        fontSourceDir: './node_modules/font-awesome/fonts/*',
        fontTargetDir: '/stuff/build/prod/fonts/'
};

        console.log('  build font: ' + font.fontSourceDir + ' > ' + font.fontTargetDir);
        console.log('              current-Dir: ' + shell.pwd());
        shell.mkdir('-p', font.fontTargetDir);
        shell.cp('-R', font.fontSourceDir,  font.fontTargetDir);
```

I get the error

```
  build font: ./node_modules/font-awesome/fonts/* > ./stuff/build/prod/fonts/
              current-Dir: /opt/jenkins/jobs/example.com_website--dev-preview/workspace
shell.js: internal error
Error: ENOENT, no such file or directory './node_modules/font-awesome/fonts/*'
    at Object.fs.statSync (fs.js:689:18)
    at /opt/jenkins/jobs/example.com_website--dev-preview/workspace/node_modules/shelljs/src/cp.js:148:21
    at Array.forEach (native)
    at Object._cp (/opt/jenkins/jobs/example.com_website--dev-preview/workspace/node_modules/shelljs/src/cp.js:144:13)
    at Object.cp (/opt/jenkins/jobs/example.com_website--dev-preview/workspace/node_modules/shelljs/src/common.js:240:23)
    at /opt/jenkins/jobs/example.com_website--dev-preview/workspace/stuff/build-scripts/build-tasks-def.js:312:15
    at /opt/jenkins/jobs/example.com_website--dev-preview/workspace/node_modules/async/lib/async.js:181:20
    at Object.async.forEachOf.async.eachOf (/opt/jenkins/jobs/example.com_website--dev-preview/workspace/node_modules/async/lib/async.js:233:13)
    at Object.async.forEach.async.each (/opt/jenkins/jobs/example.com_website--dev-preview/workspace/node_modules/async/lib/async.js:209:22)
    at Object.exports.buildFonts (/opt/jenkins/jobs/example.com_website--dev-preview/workspace/stuff/build-scripts/build-tasks-def.js:308:11)
npm ERR! weird error 1
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0
```

Using ubuntu with `apt-get install nodejs-legacy` in version

```
# npm -version
1.3.10

# node -v
v0.10.25
```

Do I have the wrong node version or is this really a bug?

**Comment by nfischer** [comment]
Hi @gruenebe, thanks for reporting this issue!

This was a breaking change we introduced in v0.6 in order to get closer to bash compatibility. The command you're writing would normally fail in bash, so we thought it should fail in ShellJS too.

To get the behavior you want, using v0.6 (which I recommend), you can change fontSourceDir from ending in "fonts/*" to merely "fonts/" or "fonts". This should be more consistent with how a bash script would work.

If changing your script is not an option, I would recommend switching back to requiring v0.5.3 specifically.

If you can run the commands as-is in bash, but not in shelljs v0.6, please let us know, and we can fix this. Or if you encounter any other issues migrating to v0.6, post them on here and we can help. Otherwise, feel free to close the issue.

**Comment by gruenebe** [comment]
ok cool, thanks for the answer. I was previously checking back with the documentation and there is stille the wildcard. Maybe remove it to not confuse other people :)

**Comment by nfischer** [comment]
Oh whoops! Thanks for pointing that out. I'll try to fix that today. If the rest of your migration goes smoothly, feel free to close this issue (or I'll close it once the docs get fixed)

**Comment by gruenebe** [comment]
no problem, I know the hassle :)
we can close it I think. Thanks a lot.

**Comment by nfischer** [comment]
@gruenebe the docs should now be a bit better. Thanks for bringing this to our attention (and for trying out the latest release!) :+1:

**Comment by gruenebe** [comment]
of course no problem :)

Maybe you should remove the wildcard thingy here too

![wildcard](https://cloud.githubusercontent.com/assets/12599965/12865905/700699e4-ccbb-11e5-82c0-b025730d44de.png)

by the way. I love the tool since I like my nodejs scripts plattform independant. I wrote my own little static-website generator with shelljs, nunjucks a.s.o. I love it :smile:

**Comment by nfischer** [comment]
@gruenebe the wildcard is still accepted. The change was that it would previously accept (and actually require) a wildcard in some situations where Bash would not support it. In those examples, `/home/tmp/` presumably exists (which I see now isn't very obvious, so I'll try to think of a better target directory). In your case, I suspect that your destination directory didn't already exist, which is why it had the error.

I'm glad to hear the tool has helped out! I agree, the platform independence is the biggest win for me personally :+1:

**Comment by flaki** [comment]
I think this might still be having issues.
I'm on Windows 10, I'm trying to copy the built files of `prosemirror` to a dist directory - but I get the following error:
```
> node -r shelljs/global -e "mkdir('-p', 'dist/prosemirror'); cp('-R', 'node_modules/prosemirror/dist/*', 'dist/prosemirror');"

shell.js: internal error
Error: ENOENT: no such file or directory, stat 'C:\Users\Flaki\data\sync\node_modules\prosemirror\dist\*'
    at Error (native)
    at Object.fs.statSync (fs.js:844:18)
    at C:\Users\Flaki\data\sync\node_modules\shelljs\src\cp.js:148:21
    at Array.forEach (native)
    at _cp (C:\Users\Flaki\data\sync\node_modules\shelljs\src\cp.js:144:13)
    at C:\Users\Flaki\data\sync\node_modules\shelljs\src\common.js:240:23
    at [eval]:1:34
    at Object.exports.runInThisContext (vm.js:54:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:409:26)
```

Obviously, the `*` folder doesn't exist, but inside dist, there is plenty of data (all folders btw). I'm running this inside cygwin, but running it from the Windows Commandline throws the same error.

I'm on shelljs v0.6.0, node --version v4.4.0, npm --version 2.14.20.

**Comment by nfischer** [comment]
@flaki thanks for verifying against master. Master branch should be pretty stable for now, so you could get away with installing from `github:shelljs/shelljs` until 0.7 comes out later this week.

**Comment by nfischer** [comment]
Sorry for the delay. v0.7 just got released. Let me know how it works for you
