### ISSUE TITLE
We need sed -n ?

### ISSUE THREAD

**Issue by hemanth** [shelljs/shelljs#38]
Some like `sed('-n','/FOO/,/BAR/p',cat("cats.txt"));`  
says  `sed: option not recognized: n`

**Comment by nfischer** [comment]
This seems like a reasonable addition. @hemanth if you're able to submit a PR, I'd be happy to take a look.

**Comment by hemanth** [comment]
I don't even recall why I had created this issue! 

Anyway,
> By default, each line of input is echoed to the standard output after all of the commands have been applied to it.  The -n option suppresses this behavior.

Let see what best I can do here.

**Comment by nfischer** [comment]
I'm going to go ahead and close this, since it doesn't seem that useful. It looks like this would only mean that a `sed()` call returns the empty string. A suitable workaround would be to just ignore the return value instead.

If other sed modes get supported, like the `/p` mode, then we can revisit this. Feel free to open this if there's some use-case I'm overlooking.
