### ISSUE TITLE
exec Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by ArtworkAD** [shelljs/shelljs#395]
I do from shell:

    netstat -an | grep 6000 | grep ESTABLISHED

which is giving me

    tcp        0      0 someIp:6000         someIp:49256     ESTABLISHED

However using shelljs I get:

    Exit code: 1
    Program output: 
    Program stderr: Illegal instruction (core dumped)

with

    require('shelljs').exec('netstat -an | grep 6000 | grep ESTABLISHED', function(code, stdout, stderr) {
			console.log('Exit code:', code);
		  	console.log('Program output:', stdout);
  			console.log('Program stderr:', stderr);
    });

Any ideas whats wrong here?

**Comment by nfischer** [comment]
@ArtworkAD thanks for reporting this!

I just tried out a similar command on my Ubuntu system, and I saw no issues. I used this command:

```javascript
> require('shelljs').exec('netstat -an | grep 60 | grep ESTABLISHED', function(code, stdout, stderr) { console.log(code, stdout, stderr); });
```

`code` was 0, as expected (I had to try it a few times though, since the `netstat` output changes almost each run).

I suspect this is *not* a ShellJS issue, since [this thread](http://en.sfml-dev.org/forums/index.php?topic=14713.0) talks about the "illegal instruction" error message possibly involving invalid assembly instructions (and all our code is pure JS). So I'm going to close this issue for now.

If you can run the command using ShellJS's native [`exec` function](https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback) but not with the ShellJS function, please ping this thread and we can revisit the issue (otherwise I suspect it may be an issue with one of your binaries).

**Comment by ArtworkAD** [comment]
@nfischer the native exec function gives the same error. It used to work for me on ubuntu too. However I switched to alpine linux which is based on busybox and it stopped working.

**Comment by nfischer** [comment]
So I would suspect that this is specific to `node` then. This sounds like an issue outside of our code base.
