### ISSUE TITLE
exec('nohup node some.js &')

### ISSUE THREAD

**Issue by sarbbottam** [shelljs/shelljs#426]
Not sure if its a bug rather question.

* node - 5.10.0
* shelljs - ^0.6.0
* os - OS X 10.11.4

---
Can I do something like:

```js
// index.js
require('shelljs/global');
const path = require('path');
const target = path.join(process.cwd(), process.argv[2])
exec('nohup node ./watcher.js ' + target + '&');
```
```js
// watcher.js
const fs = require('fs');

function watch(dir) {
  fs.watch(dir, (event, filename) => {
    if (filename) {
      // do something
    }
  });
}

watch(process.argv[2]);
```

```sh
node src/index.js ./test/fixtures
```

---

I expect the `index.js` to terminate and on `ps -ef | grep watcher` to find the `process` corresponding to `watcher.js` listed

In practice it doesn't. Is it by design?

**Comment by ariporad** [comment]
Hi @sarbbottam,

For me this is resulting in `index.js` never exiting, is the same happening for you? 

I'm not really sure *_why_* that's happening. @nfischer, you know a lot more about unix than me, any ideas?

**Comment by sarbbottam** [comment]
>For me this is resulting in index.js never exiting, is the same happening for you?

Yes

If I use `const exec = require('child_process').exec;` instead of `require('shelljs/global');` it works for me.
as [suggested in this gist](https://gist.github.com/supersha/6913695)

**Comment by kevin-smets** [comment]
Should this be closed? Seems like a legitimate bug, no?

**Comment by nfischer** [comment]
@kevin-smets thanks for following up on this issue.

However, this is not a ShellJS bug. `child_process.execSync()` and `child_process.exec()` both have the same issue, so there's nothing we can do here (our `.exec()` is built upon those).

For this specific example, here's some thoughts:

 - Use [child_process.fork()](https://nodejs.org/api/child_process.html#child_process_child_process_fork_modulepath_args_options) instead. This is much safer and more robust for executing other scripts asynchronously
   - This is cross-platform. The example above is unix-only (depends on `nohup` and `&`)
   - This works even if your version of `node` is installed under a different name (e.g. `nodejs` on Ubuntu)
   - You're safe from shell expansions you might not expect and other security risks
 - Why do you really want to start a process without waiting for it to finish?
   - If you really want to start a job and continue using your shell, why not invoke it yourself with a `&` on the end?
   - If you want your program to start a job in the background while it runs, async (like `.fork()` above) should be sufficient
   - When your program has finished doing useful work, it can clean up responsibly and kill the child process with [`.kill()`](https://nodejs.org/api/child_process.html#child_process_child_kill_signal). Otherwise, you've got processes running around on their own on your system (yikes!)

**Comment by kevin-smets** [comment]
I went with spawn since it was an actual command, not a module I need to have running in the background. I tried shelljs + `&` first, then `nohup` which was certainly not my preference because of what you mentioned. Thanks for the explanation!

**Comment by mncharity** [comment]
Another option is:

    const { spawn } = require('child_process')
    spawn( command, args, { detached:true, stdio:'ignore' }).unref()

Or  `stdio:'inherit'`, for terminal io.
