### ISSUE TITLE
shelljs@0.7.0 does not work with nyc test coverage module

### ISSUE THREAD

**Issue by bcoe** [shelljs/shelljs#438]
### Node version:

v5.8.0

### ShellJS version (the most recent version/Github branch you see the bug on):

0.7.0

### Operating system:

OSX

### Description of the bug:

`shelljs@0.7.0` no longer works with https://github.com/bcoe/nyc for test coverage, my guess would be it's related to an interaction between `spawn-wrap` and `shelljs`.

### Example ShellJS command to reproduce the error:

```javascript
    it('populates changelog with commits since last tag by default', function () {
      fs.writeFileSync('package.json', JSON.stringify({
        version: '1.0.0'
      }), 'utf-8')

      commit('feat: first commit')
      shell.exec('git tag -a v1.0.0 -m "my awesome first release"')
      commit('fix: patch release')

      shell.exec(cliPath).code.should.equal(0)

      var content = fs.readFileSync('CHANGELOG.md', 'utf-8')
      content.should.match(/patch release/)
      content.should.not.match(/first commit/)
    })
```

Here's a branch exhibiting the problem:

https://github.com/conventional-changelog/standard-version/pull/29

CC: @nexdrew, @addaleax

**Comment by ariporad** [comment]
Hi @bcoe,

Any chance you could provide a more generic shelljs command to reproduce the error?

Thanks so much!

**Comment by addaleax** [comment]
Hi @bcoe, thanks for ccing me in this! b63dde5d1a2d5f55ff78a7a74de371124100ed0a seems like the change in shelljs that lead to this… definitely looking into it. :smile:

**Comment by addaleax** [comment]
Sooooo… I wouldn’t consider it a bug in shelljs, and I’m going to write another PR against spawn-wrap, so you can stop reading here if you want. The following explanation is also definitely over-long, but I don’t really know the audience here.

@ariporad Don’t know if you are familiar with [nyc](https://github.com/bcoe/nyc), but it’s essentially a code coverage tool that automatically instruments the code in subprocesses. For example, one can run `nyc npm test` and see what parts of the code were covered by `npm test`, even though `npm` spawns the test script in a subprocess.

nyc achieves this using [spawn-wrap](https://github.com/tapjs/spawn-wrap), a module by izs that monkey-patches `child_process` internals. Whenever a new child process is spawned, it tries its best to determine if that’s a Node.js process or not, and if so, executes it using the wrapper script rather than directly using the “real” Node.js executable.

When spawning children using the shell, this check simply looks at the first argument after `sh -c` (or its equivalent) and checks the basename of that file for being `node` or something similar. In the case of shelljs, it’s `"/usr/bin/node"` or similar, due to [this line](https://github.com/shelljs/shelljs/blob/b162a2ffe6c99e49be6a00a7a5b06a4635e077a0/src/exec.js#L61). `path.basename` returns `node"` for that then, and spawn-wrap is thrown off by the extra `"` character. That’s all. :)

**Comment by ariporad** [comment]
@addaleax: Hmm... That's quite strange. Thanks so much!
