### ISSUE TITLE
[ Feature idea ] synchronous sleep command

### ISSUE THREAD

**Issue by nfischer** [shelljs/shelljs#441]
I'm sure something like this has been implemented before (and I can think of a few simple ways to implement it off the top of my head), but I think it would be beneficial for us to implement a synchronous `sleep()` command that works similarly to [unix sleep](http://linux.die.net/man/1/sleep).

Usage would be as follows:

```javascript
cd('mydir');
touch('file.txt'); // update the time stamp
sleep(1); // sleep for a second
// Now we're at least 1 second after that updated time stamp
```

One practical use case I can imagine would be for [this line](https://github.com/shelljs/shelljs/blob/master/test/touch.js#L59) in our test script, since we want to verify that time stamps are actually changed before and after the sleeping.

**Comment by ariporad** [comment]
Here's my $0.02: I don't think we should add this, because:

1. Node is designed to very specifically not do this.
2. There are a lot of modules on npm which do exactly this.
3. There's not (AFAIK), a way to do this that's both performant and doesn't require a native extension.

That being said, #402 does require something like this, so if we want to do that, we might need this.

**Comment by nfischer** [comment]
Closing this, because I released [shelljs-plugin-sleep](https://github.com/nfischer/shelljs-plugin-sleep).
