### ISSUE TITLE
exec('cd mydir') fails silently

### ISSUE THREAD

**Issue by esinek** [shelljs/shelljs#496]
### Example ShellJS command to reproduce the error:
The following fails. I am outputting my shelljs calls to a logfile and I would like to be able to replay that logfile (or parts of it without running the entire script again - debugging, yo), which is why I'm not using cd and instead trying to use exec for all commands. `exec('cd mydir')` doesn't fail verbosely, but instead fails silently (note: if mydir exists, it fails silently and doesn't change into that dir. if mydir doesn't exist, the failure is clear with an appropriate message)
```
exec('cd mydir')
```

**Comment by ariporad** [comment]
Hi @esinek!

Yes, `cd` is not supported by `exec`. This is because `exec` spawns a child-process, and child-processes cannot change their parent's cwd. For example, `exec('cd baz; myCommand');` would change the cwd for `myCommand`, but not for node.

I'm not really sure why you're using all `exec`s, could you elaborate on that problem a bit more? However, one possible solution to your problem might be [`pushd`](https://github.com/shelljs/shelljs#pushdoptions-dir---n--n)/[`popd`](https://github.com/shelljs/shelljs#popdoptions--n--n).

I'm going to close this issue, but feel free to re-open if I've misunderstood the problem.

**Comment by esinek** [comment]
Hi @ariporad,

Because the script I'm running pulls from several config files and runs many, many commands, I wanted a way to inspect all the commands that were run (and the sequence of those commands), and if I wanted, be able to re-run the entire set (or a subset) of commands from that time without touching the config files or my main script - in case I wanted to try something quick and dirty to test a hypothesis.

What I've done is put a small wrapper around exec, which will log the command to a text file. This wrapper is used by the main script to generate the text file. Using this generated text file, I can see exactly what commands and in what sequence were executed. It's also a quick way to generate a reusable set of commands that can be executed without the main script and config files.

I also wrote a simple readline/exec script that reads from that text file and executes each command in sequence. This way, I can recreate the exact steps - great for the entire top to bottom execution or a subset of commands to try something new out.

I hope that helps understand why I wanted to use cd from within exec.

I understand the issues involved and why I can't use exec for cd.

**Comment by nfischer** [comment]
@esinek why not try [`set('-v')`](https://github.com/shelljs/shelljs#setoptions) (invokes [`config.verbose`](https://github.com/shelljs/shelljs#configverbose))? Seems like it was made for this purpose. It'll output it in a Bash-like syntax to stderr--should be pretty easy to see what's going on then.
