### ISSUE TITLE
ShellJS: internal error Error: EBUSY: resource busy or locked, lstat 'C:\pagefile.sys'

### ISSUE THREAD

**Issue by bertofer** [shelljs/shelljs#514]
### Node version (or tell us if you're using electron or some other framework):

4.3.1, using electron
### ShellJS version (the most recent version/Github branch you see the bug on):

0.7.2
### Operating system:

Windows 10
### Description of the bug:

When trying to ls on C:\, it fires the following error:

```
ShellJS: internal error
Error: EBUSY: resource busy or locked, lstat 'C:\pagefile.sys'
    at Error (native)
    at fs.lstatSync (fs.js:982:18)
    at Object.fs.lstatSync (ELECTRON_ASAR.js:238:16)
    at pushFile (C:\Users\alberto\Projects\quercus\node_modules\shelljs\src\ls.js:63:25)
```
### Example ShellJS command to reproduce the error:

``` javascript
let sh = require('shelljs')
sh.cd('C:\\')
sh.ls('-lA')
```

**Comment by bertofer** [comment]
Could something like this be an approach? 
```javascript
function pushFile(abs, relName, stat) {
    if (process.platform === 'win32') {
      relName = relName.replace(/\\/g, '/');
    }
    if (options.long) {
      try {
        stat = stat || fs.lstatSync(abs);
      } catch (e) {
        console.log(e.code)
        stat = {}
      } finally {
        list.push(addLsAttributes(relName, stat));
      }
    } else {
      // list.push(path.relative(rel || '.', file));
      list.push(relName);
    }
  }
```

It's done fast, not a real solution at all. Problem with this is you need to test for any function if it exists or not, and doesn't specify that a file was locked. 

Any ideas?

**Comment by nfischer** [comment]
@bertofer Sorry, I didn't notice this until now!

It looks to me like we don't have permission to read that file? Why would that be?

I'm not opposed to this as a PR if it's the best approach. If there's a way we can stat the file, that would be even better.

Some points:

 - Please remove the `console.log()`
 - Please add a test. If you can find a way to repro this on unix (perhaps by changing permissions), that would be ideal. Otherwise, add a Windows-specific test-case (just skip if `process.platform !== 'win32'`).

**Comment by nfischer** [comment]
Closing this, since we don't officially support electron. I see that some ASAR stuff is mentioned, perhaps you might find a suitable workaround in our [wiki page](https://github.com/shelljs/shelljs/wiki/Electron-compatibility).
