### ISSUE TITLE
Feature request: ls -L option

### ISSUE THREAD

**Issue by frandiox** [shelljs/shelljs#563]
Hello! Do you think it would be interesting to add an option for `ls -RAL`? Just like `ls -RA` but also following symlinks. I think `ls -RA` is supported right now but there is no `L` for `ls`.
Thanks!

**Comment by nfischer** [comment]
@frankdiox sure, I see no reason why not. Pull requests are more than welcome!

What is the use-case for this? I can't see how `ls -RAL` and `ls -RA` would ever differ (it seems like `-L` only takes effect when the `-l` flag is used).

**Comment by nfischer** [comment]
@frankdiox If you'd like to add a PR, you can do so by taking a look at [this line](https://github.com/shelljs/shelljs/blob/master/src/ls.js#L63) and [this one](https://github.com/shelljs/shelljs/blob/master/src/ls.js#L75).

Thanks!

**Comment by frankdiox** [comment]
@nfischer Thanks! I'll try to check it when I have some time.

If I'm not mistaken, a directory symlink is just printed as a single line with `ls -RA`, but it actually follows the link and prints its content with `ls -RAL`. I have [a CLI](https://github.com/monaca/monaca-lib/blob/master/src/monaca.js#L1326) that needs to copy all the files recursively in a directory and I'd like to use symlinks inside. I guess it's not super common so it's not high priority.

**Comment by nfischer** [comment]
@frankdiox Ah, you're correct. So it looks like `-L` changes behavior for the recursive case as well as the `-l` case.

If you're trying to copy things recursively and follow links, have you looked at [`cp -rL`](https://github.com/shelljs/shelljs#cpoptions-source_array-dest)?

**Comment by frankdiox** [comment]
@nfischer Hi! Sorry for the late reply, I just used again the CLI and remembered about this issue :sweat_smile: 
I've looked into it a bit and I think the problem is actually [in this line](https://github.com/shelljs/shelljs/blob/master/src/ls.js#L85). Glob is not following symlinks. I've tried with [`follow: true` in the options](https://github.com/isaacs/node-glob/blob/master/changelog.md#45) but it still doesn't follow :neutral_face:

I cannot use `cp -rL` because it needs to "copy" the files to a mobile device through the network, is not a real copy.

**Comment by nfischer** [comment]
@frankdiox thanks for investigating this. That's strange that it wouldn't follow with that option.

Could you please give a minimal example on which the behavior reproduces?

**Comment by frankdiox** [comment]
@nfischer Nevermind, looks like there was something wrong in my environment. I tried exactly the same and it now works well. I'll also modify the two lines you pointed out in order to make it work without `R` option as well. I'll make a PR in a while :smile:
