### ISSUE TITLE
feature: GNU Parallel 

### ISSUE THREAD

**Issue by tomdavidson** [shelljs/shelljs#585]
Implement [GNU Parallel](https://www.gnu.org/software/parallel/parallel_tutorial.html) ([intro](https://www.codeword.xyz/2015/09/02/three-ways-to-script-processes-in-parallel/)). I'm primarily after usage with shx in npm run scripts.

**Comment by nfischer** [comment]
@tomdavidson we probably won't add support for this here, since it's not a standard (i.e. available by default) unix command.

This would make a good [shelljs plugin](https://github.com/shelljs/shelljs/wiki/Using-ShellJS-Plugins), though (and shx has support for exposing such plugins).

Closing this, but we can reopen if there's strong incentive from the community for this. I'd rather see it implemented as a plugin first, before we merge it into core.
