### ISSUE TITLE
unable to execute ionic command with shell js 

### ISSUE THREAD

**Issue by jpca999** [shelljs/shelljs#640]
Ionic installed globally 

![image](https://cloud.githubusercontent.com/assets/1026325/21583931/0db47d90-d063-11e6-8bb7-e0a3e88b1389.png)

Error message: 

![image](https://cloud.githubusercontent.com/assets/1026325/21583933/18a7c478-d063-11e6-9371-1d9ca968c012.png)

**Comment by nfischer** [comment]
@jpca999 did you copy-paste that code from the internet? Those quote marks don't look quite right around `ionic serve -port 81` (try retyping the quote characters, you should expect to see syntax highlighting). See [this page](https://www.cl.cam.ac.uk/~mgk25/ucs/quotes.html) for more info.

Closing this, because this has nothing to do with ShellJS.

**Comment by jpca999** [comment]
No I don't did not copy paste the code

**Comment by nfischer** [comment]
@jpca999 Why are you intentionally typing strange quote characters? Specifically, why are you typing U+2018 (LEFT SINGLE QUOTATION MARK) and U+2019 (RIGHT SINGLE QUOTATION MARK)? Those are not valid quote characters in JavaScript, you need to use U+0027 (APOSTROPHE)
