### ISSUE TITLE
Copying recursively from parent into subdirectory fills disk

### ISSUE THREAD

**Issue by rajsite** [shelljs/shelljs#644]
### Node version (or tell us if you're using electron or some other framework):
v6.9.1

### ShellJS version (the most recent version/Github branch you see the bug on):
v0.7.5

### Operating system:
Windows

### Description of the bug:
Doing a recursive copy of a parent directory into a subdirectory ends up recursing on itself and filling the disk with files.

As a workaround I put in a check using [path-is-inside](https://www.npmjs.com/package/path-is-inside) to check for that case and warn the user in my script.

### Example ShellJS command to reproduce the error:

```
file layout before
D:/build/index.html
D:/build/webservice/
```

```javascript
shelljs.cp('-R', 'D:/build/', 'D:/build/webservice');
```

```
file layout before killed
D:/build/index.html
D:/build/webservice/index.html
D:/build/webservice/webservice/index.html
D:/build/webservice/webservice/webservice/index.html
...
```

**Comment by nfischer** [comment]
Hmmm... this sounds like it is a ShellJS bug. My concern is that the unix behavior seems pretty weird. It'll actually start doing the copying, and will fail after recursing once.

```sh
$ ls -R ~/foo/
/home/user/foo:
bar

/home/user/foo/bar:
$ cp -r ~/foo ~/foo/bar
cp: cannot copy a directory, ‘/home/user/foo’, into itself, ‘/home/user/foo/bar/foo’
$ ls -R ~/foo/
/home/user/foo:
bar

/home/user/foo/bar:
foo

/home/user/foo/bar/foo:
bar

/home/user/foo/bar/foo/bar:
```

It copies `foo` into `bar`, then `bar` into the new `foo`. Then it fails when trying to copy the new `foo` into the new `bar`.

It would make more sense to me to just refuse to copy at all, but perhaps this is difficult to detect in general (due to symlinks)?

**Comment by freitagbr** [comment]
Testing `cp` on macOS 10.11.6, and the copying continued until the path was too long. As @nfischer mentioned, `cp` on linux has a safeguard against this, so we ought to implement the same safeguard in ShellJS.

**Comment by nfischer** [comment]
To me, it sounds like it'll be rather difficult to implement a good safe guard, since folders can have different names and different paths due to symlinks.

Unless POSIX specifies a behavior, I think this is something we should leave to the users to step around. If we insist on adding a safety check to protect users, I think the simplest check would be a path-is-inside check (only for directories) and failing before attempting to copy.

Although, it should be noted that [path-is-inside](https://github.com/domenic/path-is-inside) itself doesn't even work correctly for OS X paths, which are actually case insensitive.

**Comment by nfischer** [comment]
Closing this, since POSIX appears to not specify a behavior. If I'm mistaken, please ping this issue.

I suggest users just be careful about using the function so as to avoid situations like this. That doesn't sound unreasonably difficult, especially since modules like `path-is-inside` might work well in particular situations.
