### ISSUE TITLE
Snyk "high severity" issue

### ISSUE THREAD

**Issue by Unitech** [shelljs/shelljs#766]
Hello,

Is there any plan to fix this security issue detected by Snyk? It breaks some of our users builds

https://snyk.io/test/npm/shelljs

![image](https://user-images.githubusercontent.com/757747/29739502-ce445738-8a3f-11e7-9ae0-87c4266eeaf2.png)

Thanks,

**Comment by freitagbr** [comment]
Hi @Unitech,

The issue detected is the `shell.exec` API, which uses `child_process.exec` from Node.js core internally. The issue is that one could potentially pass user-input directly to the function. In order to maintain API backwards-compatibility, we cannot change this particular method, and so we are working on introducing a new, safer API in https://github.com/shelljs/shelljs/pull/524.

Are your users depending on ShellJS directly, or through another dependency? If they are depending on it directly, it is enough to just not pass un-sanitized input to `shell.exec`. If it is through a dependency, you could make sure that `shell.exec` is not passed input through its API somehow. [ESLint](https://github.com/eslint/eslint), for example, does not use `shell.exec` in its API, so it is safe.

**Comment by Unitech** [comment]
Hello @freitagbr 
I understand the problem. Snyk "security detection" is really too simplistic... No we do not pass anything variable to shelljs, we just use the .which method and one .exec...
Thanks for your answer

**Comment by nfischer** [comment]
The vulnerability is known. As @freitagbr points out, it's all about how you use it. `shell.exec('printf foo')` is totally safe, however `shell.exec('printf ' + msg)` might not be.

`shell.which()` has no known vulnerabilities 😄
