### ISSUE TITLE
test() does not support -w and -x options

### ISSUE THREAD

**Issue by dundalek** [shelljs/shelljs#768]
These are sometimes useful and are not supported as of latest shelljs (v0.7.8):

- -w file exists and write permission is granted
- -x file exists and execute permission is granted

Usage:
```javascript
require('shelljs').test('-x', '/bin/bash')
// => test: option not recognized: x

```

It can be implemented using `fs.accessSync`. Would you be interested in a PR?

**Comment by nfischer** [comment]
@dundalek that approach SGTM as long as we can support Windows. We unfortunately had to drop a lot of `chmod` support because Windows handles modes very differently. Take a look at [test/chmod.js](https://github.com/shelljs/shelljs/blob/master/test/chmod.js) for all the `skipOnWin` tests.

Feel free to send a PR with tests. Appveyor will verify if the feature works for Windows.

**Comment by dundalek** [comment]
Yeah, good point. It would do nothing on windows, nevermind.

**Comment by nfischer** [comment]
Maybe `-w` is ok? It seems to be allowed on Windows.
