### ISSUE TITLE
Long-running async process prevents script from exiting

### ISSUE THREAD

**Issue by csvan** [shelljs/shelljs#793]
### Node version (or tell us if you're using electron or some other framework):
8.6
### ShellJS version (the most recent version/Github branch you see the bug on):
0.7.7
### Operating system:
Windows 7, CentOS 7
### Description of the bug:
Starting some long-running process with `exec` and the `async:true` option in a script prevents the script from exiting. Running it from the terminal will just leave it hanging until a SIGINT is sent.

**Comment by csvan** [comment]
So, a trivial fix to this is to explicitly invoke `process.exit(0)` at the end of the script, but is this really expected behavior?

**Comment by nfischer** [comment]
Yes, this is expected behavior. Node will not exit until all async jobs are done or you call `process.exit()` (or, if you prefer, `shell.exit()`). Why do you want to kill your script before your job is done?

**Comment by mcintyre94** [comment]
We came across this trying to replicate an actor model - basically that we hit an endpoint, which in the background will kick off a long running script, but we want to return an OK right away instead of keeping the request alive until the script finishes. We're using Lambda so keeping requests alive when they don't care about the response is wasteful. We just fell back to native Node `child_process` here:

```
const { spawn } = require('child_process');
const subprocess = spawn('./script.sh', {
    detatched: true,
    stdio: 'ignore' // ignore parent terminating, continue running
})

console.log('continuing...') // runs immediately
subprocess.unref() // don't wait for subprocess, exit script
```

This will exit the script immediately while allowing the child subprocess to continue running for as long as it needs. It's definitely an unusual case, but hopefully that helps anyone else trying to do a similar thing! :)
