### ISSUE TITLE
support for node-0.10.* is broken

### ISSUE THREAD

**Issue by gcbw** [shelljs/shelljs#814]
this PR seems to have a race condition on when it exports the polyfill for Object.assign and when it uses it. https://github.com/shelljs/shelljs/pull/648/files

but it is over an year old, no idea why it is only giving me problems now on node-0.10.48 

here is the test case:
```javascript
var s = require("shelljs");
s.echo('ok');
s.exit(1);
```
gives: Exited unexpectedly with code: 7 (test on runkit.com with node-0.10.48)

the stack trace is
```
node_modules/shelljs/src/common.js:31
    Object.assign(this, DEFAULT_CONFIG);
           ^
TypeError: Object function Object() { [native code] } has no method 'assign'
    at Object.config.reset (node_modules/shelljs/src/common.js:31:12)
    at Object.<anonymous> (node_modules/shelljs/src/common.js:42:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (node_modules/shelljs/shell.js:9:14)
    at Module._compile (module.js:456:26)
```

My system was using shelljs-0.3.0 until Dec. Now it installs 0.8.0 (which seems to be out for a while, not sure why i was stuck on 0.3.0.  My employer white-list being slow?)

I can work around this easily by restoring the polyfill on https://github.com/shelljs/shelljs/pull/593/files

**Comment by freitagbr** [comment]
Hi @gcbw, yes, we dropped support for versions of node below `v4` with the recent release of ShellJS `v0.8.0`. There are a few options here:

1. Use a newer version of node (`v4` or up). I would recommend this route, because recent versions of node have fixed some security issues.
2. Use ShellJS `v0.7.8`. This is the most recent version of ShellJS that still has support for node `v0.10+`. This could work, but there are some bug fixes and general improvements available with `v0.8.0`.
3. Use the old polyfill that you mentioned.

Again, I would recommend the first option. You could try installing a newer verison of node with [nvm](https://github.com/creationix/nvm).

**Comment by gcbw** [comment]
Wonder why it installed if i can see the metadata explicitly asks for node4+

strange.

well, we support several versions, think i will just drop 0.10 from our list too. thank you.

**Comment by nfischer** [comment]
> Wonder why it installed if i can see the metadata explicitly asks for node4+

I believe npm does **not** reject packages based on the engines field (by default). See [the docs](https://docs.npmjs.com/files/package.json#engines) and the note about "engine-strict". Ah well...

---

Closing this, since we're not adding v0.10 support.
