### ISSUE TITLE
How to run a exe which is a command line interface from shell js and run commands inside the opened CLI

### ISSUE THREAD

**Issue by gkvappium** [shelljs/shelljs#831]
Hi,

I have a mobile automation framework that is typescript based . Currently I have an exe file that needs to be integrated into this framework.

This exe is a command line interface tool which actually helps me in getting various values from the connected headset. So when launched, it attached to the connected USB device (say a headset) and I can fire commands like getStatus ,getPID etc and this returns a value from the connected headset. I want to fetch this data and do some assertions.

Currently with the help of shelljs, I can open the exe but cannot chain the commands and get the commands to work in the command line interface tool.

@nzakas @nfischer  any inputs?

**Comment by nfischer** [comment]
@gkvappium "Chaining commands" usually means one of the following:

```sh
$ echo foo; echo bar
$ echo foo && echo bar
$ echo foo || echo bar
$ echo foo | cat
```

If that's not what you mean, perhaps you can elaborate (also, please see if #424 is similar to what you're describing).

**Comment by gkvappium** [comment]
Hi @nfischer ,

Let me try to explain it a little bit further. When I launch the exe, it opens up a CLI and displays something like this.

CLI version 1.4.1
Parser Protocol version: 1.0.49

There's not any HID class device with vendor usage available
(Cmd) help

Documented commands (type help <topic>):
========================================
ANC_GetAdaptiveNoiseCancelationLevel  HW_GetTemperature 

So what I need to do is, once the exe gets opened, within the same instance of the opened exe, I need to fire a command like example ANC_GetAdaptiveNoiseCancellationLevel . This returns a hex value something like 0x0004 or something similar. I need to capture this value from the connected USB device.

I checked the link that was shared by you. Doesn't seem to work. I can't give some command in the stdio since it expects only certain things that needs to be given as part of this.

**Comment by nfischer** [comment]
I see. This usage is different than the "command chaining" I described in my comment. You're spawning an interactive CLI (sort of like a REPL) and then trying to input text into that REPL and capture output.

I recommend trying this out in bash first (I'll use `node` as an example REPL, since I don't know your CLI binary):

```sh
# A sample bash script, which accepts some argument and outputs the JavaScript
# toUpperCase() equivalent

jsExpression="'$1'.toUpperCase()"
commandToRun="console.log(${jsExpression})"
output="$(echo "$commandToRun" | node)"

# Note: node provides explicit support for this use case with its '-p' flag:
# node -p "$jsExpression"

echo "$output" # or do something else with the output
```

---

Some things worth noting (I'll use the term "REPL", because not all CLI tools spawn interactive prompts):

 - This starts the REPL, issues a command, then closes the REPL. You can repeat the cycle to issue a 2nd command
   - If that's OK, you can try `shell.ShellString(commandToRun).exec('node')`
   - If 2 commands really need to be in the same REPL session, I recommend `var c = child_process.execFile(...)`. You can issue commands with `c.stdin.write()` and get output with `c.stdout.on('data', callback)`.
 - If at all possible, I recommend rewriting your binary to accept commands as CLI arguments (like `node -p 'some JS code'` or `bash -c 'some bash code'`). This is more common practice.
   - There's a decent chance your REPL already accounts for this
   - If not, you would need to fork the code (or go with the previous option)

**Comment by nfischer** [comment]
> As far as the binary is concerned, I don't think rewriting the binary is an option since we do not have access to the source code

That's unfortunate. To reiterate: the "right" way to do this is to have a binary file which *actually supports doing this.* Your binary is for interactive use, not programmatic use. Unless it has a programmatic interface (e.g., node's `-p` flag I alluded to earlier), every solution will be a hack.

> How do I just get the stdout from this (0x0005)

I'm not sure I understand you 100%, so here are a few ways I might interpret your statement:

 1. "The program stdout spits out a command prompt ("`(CMD) `") and the command result ("`ancModeId = 0x0005`"). I want only the command result"
   a. It's up to you to parse out the command prompt.
 2. "The program stdout spits out a command prompt ("`(CMD) `"), the answer I want ("`0x0005`"), and some other junk I don't want ("`ancModeId = `")."
   a. Same answer, parse it
 3. "The program stdout spits out some error messages that I'm not interested in (`*** Unknown syntax`)
   a. I'll comment on EOF specifically in the below paragraph. In general, you'll have to either expect errors or be confident you're executing commands which can never error-out.

> but the problem is it's not terminating the shell after this.

This is because your binary doesn't know how to handle EOF (it doesn't support this use case). You likely need to use shell.exec() in async mode, and use [`.stdin.write()`](https://nodejs.org/api/stream.html#stream_writable_write_chunk_encoding_callback) to pipe input into the child process. When you're done sending commands over, you can [kill](https://nodejs.org/api/child_process.html#child_process_subprocess_kill_signal) the subprocess.

---

Closing this issue, because this is way out of the scope of shelljs. But feel free to continue asking questions on here, as I'm happy to advise.

**Comment by gkvappium** [comment]
Hi @nfischer,

Thanks for taking time off to elaborate this in detail.

For the moment, I've a python solution for this. EOF is being achieved by passing the actual command and lot of junk data from a text file. The cmd prompt is exiting and I also get the response from the binary. I am just filtering out what is needed from the output. I then call this file in my typescript based framework using python-shell.

But I'll try and see if the binary could be modified to accept arguments and also the other method that you've detailed out.

Thanks

**Comment by nfischer** [comment]
My pleasure. Glad to hear you've got a solution, hopefully you'll be able to add support for a programmatic interface upstream. Best of luck!

**Comment by gkvappium** [comment]
Hi @nfischer ,

Just a simple query. Might be silly, but can't figure out a way to actually get the return value outside the inner function.

Say if I have a function,

async commands(){
    exec('some_long_running_process', function(code, stdout, stderr) {
    console.log('Exit code:', code);
    console.log('Program output:', stdout);
    console.log('Program stderr:', stderr);
    });
        return stdout
    }

so when I assign this function to a var in another file, I always get undefined. So is there a way to access stdout globally? Basically I want to return the inner function value to an outer function so this can be assigned to a var in another file.

    var data = commands() //Will result in undefined.

I need to have this for modularity since I have lot of commands.

**Comment by nfischer** [comment]
You can assign to a property on an object.

```js
var holder = {};
exec('some_process', (code, stdout, stderr) => {
  holder.val = code;
});
// holder.val is undefined, because the callback hasn't completed yet
// But after the callback fires, holder.val should have the expected value
```

**Comment by gkvappium** [comment]
Thanks @nfischer . I was able to achieve this using promises. Did something like this.

    export class Commands {
        runCommands(){
            return new Promise(function (resolve, reject){
                pythonShell.run(scriptPath,function (err, result){
                if (err) reject(err);
                else resolve(result[7]);
              });
            });
          }
        }

I can then use it something like let output = await runCommands()  //Since all the tests are async functions
