### ISSUE TITLE
Streaming ls

### ISSUE THREAD

**Issue by xixixao** [shelljs/shelljs#843]
I love shelljs, it feels like a much better tool for making scripts than native Node APIs. One thing I'm missing is async/streaming ls. I know there is a separate issue for async, but I think that is tending towards

```es6
await shell.ls('folder/**/*.js')
```
whereas I would like to have
```es6
shell.ls('folder/**/*.js', fileName =>
  console.log(fileName)
);
```
Not sure what the best API is, but it would be nice to have this included. Essentially https://www.npmjs.com/package/glob-fs#stream

**Comment by nfischer** [comment]
How about

```js
shell.ls('pattern').forEach(fileName => {
  console.log(filename);
});
```

This is not async, but it's essentially the interface you to use.

Closing this, because async is a long way off, and tracked in other bugs. In the future, if we do support async, then we'll probably return all filenames at once (not exactly what you asked for, but I would guess that's most appropriate for most use cases).

**Comment by xixixao** [comment]
For posterity: The problem with returning all files at once is that once you get to 1000s of files it gets slow. It's reasonable to write shell scripts operating on large number of files.

**Comment by xixixao** [comment]
Oh, and for the API, I guess better would be ala https://github.com/shelljs/shelljs/issues/396:

```es6
await shell.ls('pattern').streamForEach(fileName => {
  console.log(filename);
});
```
this could be consistent for all "streaming" commands
