### ISSUE TITLE
But why?

### ISSUE THREAD

**Issue by inf3rno** [shelljs/shelljs#923]
Can you enlighten me why we need this? I am fond of the don't try to reinvent the wheel principle, and I understand that for command line it is better to have (cryptic) abbreviations, because it is faster to type, but if we are writing code in a text file, we usually have auto completion, so we could easily write something readable, which does not have to be short.

If I take your example literally:
```js
var shell = require('shelljs');

if (!shell.which('git')) {
    shell.echo('Sorry, this script requires git');
    shell.exit(1);
}

// Copy files to release dir
shell.rm('-rf', 'out/Release');
shell.cp('-R', 'stuff/', 'out/Release');

// Replace macros in each .js file
shell.cd('lib');
shell.ls('*.js').forEach(function (file) {
    shell.sed('-i', 'BUILD_VERSION', 'v0.1.2', file);
    shell.sed('-i', /^.*REMOVE_THIS_LINE.*$/, '', file);
    shell.sed('-i', /.*REPLACE_LINE_WITH_MACRO.*\n/, shell.cat('macro.js'), file);
});
shell.cd('..');

// Run external tool synchronously
if (shell.exec('git commit -am "Auto-commit"').code !== 0) {
    shell.echo('Error: Git commit failed');
    shell.exit(1);
}
```
then it is not that hard to write something human readable based on it:
```js
const shell = require('shelljs');
shell.install({git: require("shelljs-git")});

class MyTask extends shell.Task {
    execute(){
        this.gitRequired();
        this.copyFilesToRelaseDirectory();
        this.replaceMacrosInEachJavascriptFile();
        this.runExternalToolSynchronously();
    }

    gitRequired(){
        if (!this.which('git'))
            throw new Error('Sorry, this script requires git');
    }

    copyFilesToRelaseDirectory(){
        this.remove({target: 'out/Release', recursive: true, force: true});
        this.copy({source: 'stuff/', target: 'out/Release', recursive: true});
    }
    
    replaceMacrosInEachJavascriptFile(){
        const searchReplacementPairs = [
            {search: 'BUILD_VERSION', replacement: 'v0.1.2'},
            {search: /^.*REMOVE_THIS_LINE.*$/, replacement: ''},
            {search: /.*REPLACE_LINE_WITH_MACRO.*\n/, replacement: this.readFile('macro.js')}
        ];
        this.changeDirectory('lib');
        this.list('*.js').forEach((file) => {
            searchReplacementPairs.forEach((pair) => {
                this.streamEditor({source: file, search: pair.search, replacement: pair.replacement});
            });
        });
        this.changeDirectory('..');
    }
    
    runExternalToolSynchronously(){
        try {
            this.git.commit({all: true, message: "Auto-commit"});
        } catch(error){
            throw new Error("Git commit failed");
        }
    }
}

const myTask = new MyTask();
myTask.execute();
```

**Comment by nfischer** [comment]
I think this is a good question, and I think you raise good points. This is veering toward subjectivity; I don't think either API surface is necessarily superior, but your API surface isn't entirely inline with ShellJS's goals.

I'm closing this because I don't think there's any action this project should necessarily take, but here's my thoughts in-line:

---

> so we could easily write something readable, which does not have to be short.

Our API is short for consistency with unix (an explicit project goal), not to avoid typing. Although `remove()` might be clear to an English speaker, `rm` might be even clearer to a shell scripter: "remove" only vaguely implies "it removes files" while "rm" implies rm-like semantics. I don't think either is inherently superior, but since many of our users have unix backgrounds, the unix-y names seem like a slight win.

> `shell.install({git: require("shelljs-git")});`

Does "install" download a module? I would discourage this, since dynamic module downloading isn't common in the ecosystem and might surprise some users.

This line and the `shell.git` calls look similar to our [plugin API](https://github.com/shelljs/shelljs/wiki/Using-ShellJS-Plugins). You might find that interesting (if you haven't read it yet).

> `class MyTask extends shell.Task`

Are Tasks a common JS idiom? It should be possible to write a separate module to provide this API. I don't have bandwidth to maintain this, but you're welcome to write a 3rd party module (but you might want to watch this repo to keep up with the latest releases).

> it would be nice to pipe these into nodejs streams

Agree it's nice. It's not currently possible, but I hope we can change that now that we've dropped lower Node versions. It's low-priority unfortunately, but it would certainly improve performance.

**Comment by nfischer** [comment]
> You should not take this example literally, and what you were criticizing are not the important parts.

I recognize the example is to illustrate a larger point. I didn't mean to come across as nit-picky; I asked about specific parts of the example to understand them better. I've replied inline to some of your bullet points:

---

> it uses method and property names instead of strings, so you can use auto-complete in an IDE

 * **method names**: we already use these though...?
 * **property names**: I don't use an IDE, so I don't see how it can do better autocompleting these.
   * In terms of readability, I think long options pose an advantage over short options. I would be in favor of supporting `shell.touch({recursive: ...})` (filed #924).
 * If you're specifically calling out `shell.exec()`, I wrote a [less-stringy alternative](https://github.com/nfischer/shelljs-exec-proxy)

> it uses try-catch + uncaughtException instead of if-else + echo + exit

Exceptions are off by default to resemble shell scripting. You can turn them back on with [`shell.config.fatal`](https://github.com/shelljs/shelljs#configfatal).

> I think you can generate the whole thing based on the --help if you don't want to do it manually

Not sure what you mean by this.

---

> I don't see a reason why I would use your current low level API instead of a bash script, but maybe the problem is with me. Writing javascript code in a similar way as I proposed would mean a real advantage. I might write it later to replace my bash scripts, it's just not a priority currently.

Cross-platform is the main advantage over bash. Simplicity/familiarity is the main advantage over core Node APIs (like `fs`).

**Comment by inf3rno** [comment]
>     I think you can generate the whole thing based on the --help if you don't want to do it manually
> 
> Not sure what you mean by this.
> 

Currently the arguments of `rm` is hardcoded:
https://github.com/shelljs/shelljs/blob/master/src/rm.js#L4
You might be able to use the output of `rm --help` to get the list of the arguments.

Ohh I checked the code, I was completely wrong about this lib. I thought that it is using bash commands in the background...
Well then some of my arguments are based on false assumptions.
