### ISSUE TITLE
Inaccurate exec callback example in README

### ISSUE THREAD

**Issue by PepperTeasdale** [shelljs/shelljs#940]
### Node version (or tell us if you're using electron or some other framework):
11.6.0
### ShellJS version (the most recent version/Github branch you see the bug on):
2.0.3
### Operating system:
osx
### Description of the bug:
The code example shows using a callback on a synchronous call to `exec`. We expected the callback to be run, but it wasn't. It seems like the example is missing the async option? The text description seems correct, that the callback receives the arguments when *not* in synchronous mode.

### Documentation snippet that is erroneous in README.md:

```javascript
exec('some_long_running_process', function(code, stdout, stderr) {
  console.log('Exit code:', code);
  console.log('Program output:', stdout);
  console.log('Program stderr:', stderr);
});
```
> Executes the given command synchronously, unless otherwise specified. When in synchronous mode, this returns a ShellString. Otherwise, this returns the child process object, and the callback receives the arguments (code, stdout, stderr).

**Comment by nfischer** [comment]
> The code example shows using a callback on a synchronous call to exec

Not sure what you mean. Per [the docs](https://github.com/shelljs/shelljs#execcommand--options--callback) (adding emphasis now):

> async: Asynchronous execution. **If a callback is provided, it will be set to true**, regardless of the passed value (default: false).

Maybe we should also change the sentence you quoted to "... unless otherwise specified _(by `{async: true}` or by passing a callback)_."

---

> We expected the callback to be run, but it wasn't.

Not sure why that would happen. Of course, if your command runs long enough (i.e. infinitely), you won't see the callback until it _finishes_.

---

What do you mean by version = 2.0.3? We've never released that ShellJS version.

**Comment by PepperTeasdale** [comment]
Sorry, I think I missed something in the docs. I was not able to reproduce again
