### ISSUE TITLE
0.8.3 high severity vuln

### ISSUE THREAD

**Issue by dannypaz** [shelljs/shelljs#945]
### Node version (or tell us if you're using electron or some other framework):
Node 8+
### Operating system:
macOS

### Description of the bug:

Received warnings on PM2 that shelljs got tagged for a security vulnerability.

```
WS-2017-3737
More information
moderate severity
Vulnerable versions: <= 0.8.3
Patched version: No fix

Shelljs 0.8.3 and before are vulnerable to Command Injection. Commands can be invoked from shell.exec(), those commands will include input from external sources, to be passed as arguments to system executables and allowing an attacker to inject arbitrary commands.
```

**Comment by jahed** [comment]
GitHub reported this on some of my repos too and I'm trying to understand what it's complaining about. Yes, "those commands will include input from external sources", since it takes strings... What's the actual method and problem? It's strange to see this pop up without a fix or issue ticket referenced.

**Comment by thisBrian** [comment]
Additionally the security warning references [this commit](https://github.com/shelljs/shelljs/commit/7a9f8e5b7547132ea3f7e4fa47356a94d1156bb3). 

With my understanding it appears to be functioning as intended and could just be caught in an automated audit that doesn't take into account the very purpose of the package?

Perhaps someone with more insight could chime in.

**Comment by nfischer** [comment]
@thisBrian that commit didn't land.

This is a duplicate of issue #495 (also filed under issue #810).

**Comment by nfischer** [comment]
The vulnerability is limited to only `shell.exec()`, other commands are generally safer (and should be entirely safe with `shell.set('-f')`).

**Comment by dannypaz** [comment]
Does anyone know if the security vuln notification was removed/ignored from Snyk?

**Comment by duro** [comment]
@dannypaz I still see it https://snyk.io/vuln/npm:shelljs:20140723

**Comment by Beyarz** [comment]
Got the same notification from Githubs automated system

**Comment by AlvexGR** [comment]
I've got the same security alert from GitHub 2 days ago

**Comment by shumailxyz** [comment]
Any update?

**Comment by dannypaz** [comment]
For an update for you all. It must be understood that if you use the `exec` function in this library _you must_ sanitize the input yourself. From what I understand, library itself isn't vulnerable, it is the usage of the library that has the potential*.

I've reached out to whitesource software (where the origin of the github security alert is coming from) and let them know that this might be a NOOP.

At this point, the resolution is to use the github tooling or snyk tooling and ignore the alert. For github, you can view https://help.github.com/en/articles/viewing-and-updating-vulnerable-dependencies-in-your-repository (look for the dismiss button)

**Comment by nfischer** [comment]
Thanks, @dannypaz. Yes, this method's input **must be sanitized** (also: there are libraries which can sanitize input for you, but I don't have a library I'm yet ready to recommend). [shelljs-exec-proxy](https://github.com/nfischer/shelljs-exec-proxy) provides a lot of protection out of the box, although I'm not sure how well it works on Windows (help for https://github.com/nfischer/shelljs-exec-proxy/issues/17 would be appreciated).

I will acknowledge sanitizing input is non-trivial, and easy to mess up. For this reason, I still intend to provide a better (meaning, easier-to-use-correctly) replacement to `exec()` (this work is in #866). But the vulnerability Snyk reported is fundamentally part of the `exec()` API, and cannot be fixed in a backwards compatible way.

---

I do take this report seriously, and I will try to prioritize quick patches to the documentation to explain this better. I will also see if there's an input sanitization library I can recommend, and if I can write up general advice for using ShellJS securely.

It will be significantly harder to push #866 to completion, and may not be technically possible on Windows. It's really difficult to provide a meaningful extension to `child_process.{spawn,execFile}Sync()` while keeping a comparable interface. If those methods satisfy your use case, feel free to use them.

**Comment by ehmicky** [comment]
@nfischer we have had the exact same [problem with execa](https://github.com/sindresorhus/execa/pull/182#issuecomment-488679564). Snyk flagged us for using the `shell` option, but that's a little silly. This option is indeed bad in 99% cases, but there are some legitimate use cases.

After discussing with Snyk, they removed the warning. We also added an alternative method that allows passing command + arguments as a single string, but without using the `shell` option. I believe many users use the `shell` option because they want that, without understanding that their command will be prone to command injection, slower and less cross-platform.

**Comment by nfischer** [comment]
I'm in communication with Snyk right now. We've come to the mutual conclusion that it probably doesn't make sense to label ShellJS as "vulnerable," given `shell.exec()` is working as intended and it's the responsibility of dependent modules to sanitize input.

I've so far landed #950 and #951 to document this, and I've written [security guidelines](https://github.com/shelljs/shelljs/wiki/Security-guidelines) for using the project (basically, the stuff I said I would do in https://github.com/shelljs/shelljs/issues/945#issuecomment-505207287). Input from others is welcome, otherwise you can expect an update when I hear back from Snyk.

**Comment by kabirbaidhya** [comment]
Same here - getting this alert from GitHub. So, can we expect this to be patched on `0.8.4`? Any thoughts on when that might be out?

**Comment by Cyclonecode** [comment]
I totally agree with the statement that this is not an issue with shelljs. The responsibility to sanitise the input should be on the module which depends on shelljs. I mean looking on PHP for instance, try just sending the user supplied values straight into `shell_exec()` and see what happens =)
https://www.php.net/manual/en/function.shell-exec.php

**Comment by nfischer** [comment]
@kabirbaidhya no, we will not be pushing out a patch release for this, as there's no vulnerability for us to patch (kindly see the rest of this thread). The `exec()` API is working as intended; to "fix" the "vulnerability" would be to break the API contract (which I don't intend to do, but would at the very least require a semver bump).

> getting this alert from GitHub

The alert is created by Github's partner, WhiteSource. I'm [trying to get in contact](https://twitter.com/ntfschr/status/1148335844937256961) with them to take down this false positive or to at least discuss the report. I would greatly appreciate if folks on this thread can help me get in contact with this group (I'm not much of a twitter user, and I couldn't figure out the right email on their site).

**Comment by brainkim** [comment]
@nfischer After a cursory search, I found the product VP on Github (@habushaws). Maybe they can help?

**Comment by kabirbaidhya** [comment]
@nfischer Makes sense. Thanks. 
Also, the [security guidelines](https://github.com/shelljs/shelljs/wiki/Security-guidelines) makes it clear, which we'll follow; thanks for explaining it there.

**Comment by habushaws** [comment]
@nfischer @kabirbaidhya thanks for the great catch. We're looking into it and will keep you all posted. We're examining whether the vulnerability is not in shelljs, but rather in the native shell.exe, therefore, it may be the responsibility of the caller to ensure how to use it. Some users will assume it as the responsibility of shelljs, but others will not. Again, we're looking into it and will update soon.

**Comment by nfischer** [comment]
@habushaw From our perspective, it **must** be the caller's responsibility. The JavaScript language simply does not allow us, in our module, to distinguish between `shell.exec('intentionalCommand1 && intentionalCommand2')` vs. `shell.exec('intentionalCommand ' + unsanitizedUserInput)`. Please see https://github.com/shelljs/shelljs/issues/945#issuecomment-506019725 for a summary of the steps I've taken to inform callers of how to use this API correctly.

Thank you for prioritizing this. I've also sent an email to support@whitesourcesoftware.com (your site didn't leave a contact for contesting vulnerability reports), so please reach out to me via email with further questions.

**Comment by habushaws** [comment]
@nfischer @kabirbaidhya after a careful examination of this vulnerability, we've decided to remove it from our database. Thanks again for the great catch.

**Comment by travispaul** [comment]
> your site didn't leave a contact for contesting vulnerability reports

@habushaws what's the best method for contesting a vulnerability? Would be good to know when/if something like this happens again in the future. Thanks

**Comment by kabirbaidhya** [comment]
> @nfischer @kabirbaidhya after a careful examination of this vulnerability, we've decided to remove it from our database. Thanks again for the great catch.

When this vulnerability alert itself has been taken down from GitHub now, should this issue be closed?

**Comment by jimthedev** [comment]
Asking here since @habushaws is here. If I use shelljs in one of my packages and accept raw user input to be executed then will my notice be retroactively removed to my downstream? I have people on my issues board asking about this issue and just want to know how to present accurate facts around our usage of shelljs.

**Comment by nfischer** [comment]
As this has been removed by both WhiteSource (https://github.com/shelljs/shelljs/issues/945#issuecomment-512044653) and Snyk (https://snyk.io/vuln/npm:shelljs:20140723), I consider this issue to be resolved.

Any dependent modules stumbling across this issue should consult our [security guidelines](https://github.com/shelljs/shelljs/wiki/Security-guidelines).

**Comment by markhibberd** [comment]
auditjs is still reporting an issue due to it still being an open vulnerability on sonatype - https://ossindex.sonatype.org/vuln/560f37f7-6c1d-4b9c-aad3-34dcfcf218d7

**Comment by nfischer** [comment]
@markhibberd I believe sonatype is now updated: https://ossindex.sonatype.org/component/pkg:npm/shelljs. Thanks for raising this to my attention.

**Comment by IdanAdar** [comment]
```=== npm audit security report ===                        
                                                                                
                                                                                
                                 Manual Review                                  
             Some vulnerabilities require your attention to resolve             
                                                                                
          Visit https://go.npm.me/audit-guide for additional guidance           
                                                                                
                                                                                
  Low             ShellJS exec() Function Arbitrary Command Injection Weakness  
                                                                                
  Package         shelljs                                                       
                                                                                
  Patched in                                                                    
                                                                                
  Dependency of   shelljs                                                       
                                                                                
  Path            shelljs                                                       
                                                                                
  More info       https://vulndb.cyberriskanalytics.com/vulnerabilities/151992  
```

Maybe someone can reach out to cyberriskanalytics.com?

**Comment by nfischer** [comment]
@IdanAdar how did you get this warning? Does this come from `npm audit` by default, or did you configure something?

**Comment by IdanAdar** [comment]
Didn’t change anything. Straight forward npm audit

**Comment by nfischer** [comment]
Huh, I don't get the same warning. What npm version?

**Comment by IdanAdar** [comment]
6.10

**Comment by nfischer** [comment]
I just tried with 6.10.3 and couldn't repro. I wonder the module you're in (or perhaps a company-managed registry) is adding some non-default auditors.

**Comment by IdanAdar** [comment]
@nfischer It seems this is being reported only when .npmrc points to an npm repo in jFrog artifactory (which I guess has some advisory databases in its Xray product).

If you scan w/out artifactory, it's not reported...
It seems there's no way to login there to see what the advisory is about.

**Comment by IdanAdar** [comment]
I've contacted cyberriskanalytics and checking if they are going to close their advisory based on this thread and given the several vendors have done so.

@nfischer Please let know how how to contact you via email for some additional information.
