### ISSUE TITLE
Website is down?

### ISSUE THREAD

**Issue by reviewher** [shelljs/shelljs#967]
repo lists website http://shelljs.org but the site is down.  You can test at https://downforeveryoneorjustme.com/shelljs.org

**Comment by nfischer** [comment]
Thanks for catching this. I don't actually own that site, but it's supposed to just redirect to http://documentup.com/shelljs/shelljs. I think it's fine to just replace "shelljs.org" with the actual documentup URL (ideally, take advantage of this to use the "https://" scheme for the URL too).

PRs are welcome, otherwise I'll get to this eventually.

**Comment by reviewher** [comment]
So there are actually two places that shelljs.org is referenced:

1) README.md:

```md
check out [the npm
page](https://www.npmjs.com/package/shelljs) or
[shelljs.org](http://documentup.com/shelljs/shelljs).
```

Interestingly, the actual link directs to your redirect, so changing that README is an easy PR for someone else

2) github metadata

You or another project owner have to make this change.  When you go to https://github.com/shelljs/shelljs, you'll see an edit button on the right side and you can change that website field.  That is something you cannot change via PR -- it has to be done in the github web interface

**Comment by nfischer** [comment]
Ah, didn't realize it doesn't actually go to shelljs.org in the README. We should change that text to not be misleading.

I just changed the metadata field for the repo.

**Comment by reviewher** [comment]
Someone must've fixed the domain, as it seems to work now
