### ISSUE TITLE
temp files?

### ISSUE THREAD

**Issue by wmertens** [shelljs/shelljs#979]
I noticed that scripts are executed with a bunch of temp files for parameters and output. However, if the filesystem is full, that means scripts won't be able to run.

Would it not be possible to use pipes?

**Comment by nfischer** [comment]
exec-child.js needs to write its stdout/stderr to its parent process's stdout/stderr (that's usually the console, to support real-time output) as well as capture that output to send back to the parent process itself (that's so `shell.exec('some command')` returns an object with `.stdout` and `.stderr` properties). I think unix pipes could work, but I'm not familiar with node's APIs for this. Temp files are straightforward enough, but have the drawback you observed.

exec-child.js also needs to accept data which it will send to its subprocess's stdin. I think this could also be implemented with a unix pipe, so long as we can detect the end of the input and signal this to the `ChildProcess.stdin` stream, otherwise the command will hang.

We also need to pass the command arguments and the options for `child_process.exec()`. It's tempting to pass these as arguments when invoking `exec-child.js`, but the issue here is the OS has a limit for the length of commandline arguments, and we need to make sure this data doesn't exceed it (the exec options hypothetically could, since it's arbitrary JSON). We could maybe avoid file IO for the common case, but we might need to have a code path to support longer arguments.

If you're interested in trying to switch to pipes, PRs are welcome. There should be a perf win for reducing the number of temp files (even if we don't get the number down to zero).

---

Long term, the plan is to replace `shell.exec()` with `shell.cmd()`, which won't have as many special needs as `exec()`, so it shouldn't need temp files. That's tracked in #495.

**Comment by wmertens** [comment]
Hmm - if `shell.cmd()` will use pipes anyway, and it allows passing individual parameters without them being split, I don't think `shell.exec()` should get any further development - it is a clearly better API and it can be wrapped to achieve splitting. Closing this in favor of #495.
